services:
  db:
    container_name: 'db'
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./db_volume/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DJANGO_USER=$POSTGRES_DJANGO_USER
      - POSTGRES_DJANGO_PASSWORD=$POSTGRES_DJANGO_PASSWORD
      - POSTGRES_DJANGO_DB_NAME=$POSTGRES_DJANGO_DB_NAME
    ports: 
      - "55432:5432"

  jupyter:
    image: jupyter/datascience-notebook:latest
    #build:
    #  context: ./docker/jupyter
    #  dockerfile: Dockerfile
    tty: true
    user: root
    environment:
    - GRANT_SUDO=yes
    - TZ=Asia/Tokyo
    ports: 
      - "58888:8888"
    volumes:
      - ./jupyter_volume/:/home/jovyan/work 
        #command: start-notebook.sh --NotebookApp.password='sha1:YOUR_PASSWORD_HASH_VALUE'
