services:
  db:
    container_name: 'db'
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./volumes/db_volume/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DJANGO_USER=$POSTGRES_DJANGO_USER
      - POSTGRES_DJANGO_PASSWORD=$POSTGRES_DJANGO_PASSWORD
      - POSTGRES_DJANGO_DB_NAME=$POSTGRES_DJANGO_DB_NAME
    ports: 
      - "55432:5432"


  pgadmin4:
    container_name: 'pgadmin4'
    image: dpage/pgadmin4:latest
    ports:
      - 58880:80
    volumes:
      - ./volumes/pgadmin-data:/var/lib/pgadmin
      - ./config/db.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: "sanosanosano3@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "psqlAdmin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      POSTGRES_USER: $POSTGRES_DJANGO_USER
      POSTGRES_PASSWORD: $POSTGRES_DJANGO_PASSWORD
      POSTGRES_NAME: $POSTGRES_DJANGO_DB_NAME
    depends_on:
      - db

